# Generated by Django 5.1.2 on 2024-11-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_crm', '0001_initial'),
        ('hotels', '0004_hotel_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='hotels.hotel'),
        ),
    ]
