# Generated by Django 5.1.2 on 2024-11-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_crm', '0002_customer_hotel'),
        ('reservation', '0003_reservation_hotel_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationhistory',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='room',
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_histories', to='reservation.reservation'),
            preserve_default=False,
        ),
    ]
