# Generated by Django 5.1.2 on 2024-11-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_crm', '0003_remove_reservationhistory_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nid',
            field=models.CharField(default=1160474745, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='payment_method',
            field=models.CharField(choices=[('website', 'وبسایت-درگاه'), ('reservation', 'رزرواسیون-اعتباری'), ('marketplace', 'مارکت\u200cپلیس-اعتباری'), ('travelagency', 'آژانس-اعتباری')], max_length=20),
        ),
    ]
