# Generated by Django 5.1.2 on 2024-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_crm', '0004_customer_nid_alter_reservationhistory_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
