# Generated by Django 5.1.2 on 2024-10-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='base_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
