# Generated by Django 5.1.2 on 2024-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_guest_name_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'منتظر پرداخت'), ('AWAITING_CHECKIN', 'منتظر ورود'), ('CURRENT_GUEST', 'مهمان فعلی'), ('CHECKED_OUT', 'خروج کرده'), ('CANCELLED', 'کنسل شده')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
