# Generated by Django 5.1.2 on 2024-11-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_unique_identifier'),
        ('reservation', '0006_reservation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationpolicy',
            old_name='description',
            new_name='policy',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='policy_name',
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='hotels.hotel'),
        ),
    ]
