# Generated by Django 5.1.2 on 2024-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('apartment_hotel', 'هتل آپارتمان'), ('one_star', 'هتل 1 ستاره'), ('two_star', 'هتل 2 ستاره'), ('three_star', 'هتل 3 ستاره'), ('four_star', 'هتل 4 ستاره'), ('five_star', 'هتل 5 ستاره'), ('eco_lodge', 'بومگردی'), ('boutique_hotel', 'هتل بوتیک'), ('resort', 'مجتمع تفریحی'), ('motel', 'متل'), ('hostel', 'هاستل')], default='one_star', max_length=20),
        ),
    ]
