# Generated by Django 5.1.2 on 2024-11-06 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
