# Generated by Django 5.1.2 on 2024-11-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
    ]
